apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: zkip-stark-staging
  namespace: staging

namespace: staging

resources:
  - ../../base

replicas:
  - name: zkip-stark
    count: 1

configMapGenerator:
  - name: zkip-stark-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - MAX_CONCURRENT_PROOFS=5

